language: android
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_ee4c0e213626_key -iv $encrypted_ee4c0e213626_iv -in NotificationManager/release-key.keystore.enc -out NotificationManager/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: RFUdXdwSelmzWFySACCGft5V+9CgAP6k2aUnLxzCzMb/V5qrMK7Z+6B+XH7bAA3Yc3f4XYZPMXhPiRH87XZxEeKPrt99lR+hXZrkPegv63cXq8GLoX+sfujjxU+WggLyDSzhLa1jqhB39SRtXzfgsFKrnA7BZTjO4rZAD1hEb121sWslaiM2GiPgukoia3SIOmsoq46j91YqtCY63xw7b+sAWT55Qn9kCjdbGsSy3UmQUjvJdimeaAF96aXex1+HX4weIn7zBrBjTXH21vpgBkOEUhFurGqZCQkom6kJlnC0DYl5jLXuskaBZRvYa7AMdsfSXZ02KxXOxAzvHlXG7Xjad12AswVVFqYGhDo19vDSKGNAwdlXgSjXVfrUSbY+mM5ZrYuTuQfwkxWiaSzmdioWMHMdgumqDNQTfiBp5dXO9b4EYMcMglStlJV07xkWFEl6mob4WO4hn3tEWuilNeBiY1ZCi2VkuDbQEF1yjFt1TxXCk3u44PeHNejy7FqiaSkrHJ+Qs6e5PAGAs5+WpCs8rlXeVLzIswdxflMqdcnkQ84FkBnsFJmLyv6Irm0EcPBbGdsdtluN3ThL6xGLcfRsc8C9AfaUizGDIziINqhdjke5jglUf74/693bJ3FDTfGSth3v8W9oClebweWF34Byl41Q+IPYQqUZbBpsCU0=
  file: NotificationManager/build/outputs/apk/NotificationManager*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-NotificationManager
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: IbYL1SVn4Qc7q6COPtwISq/NOndxf99zVIVXYKD4+skPrrHOE6BI5ZkdIzhXcKA7muNIKwg5zBSVZyYtczzwk2k7PdeYeY3mXqkFYdHMWnB7zp45vsZLs/42eNCzox3VMsEAOUOMH25ZC7Mf4xXM6P6YZUm9aHZGvJo7HFog/AL8gb36gcwPOJNTw1ACSBKIfqW/zLVBali3eMrJ6+85PGCdToPr2G/fdVEQV7X6HfyND3vbIWvUttCnym+rOAwv7027IhtO4eAKYWSn3o4N31k0PPCifM00Zj+Hzu5gIgrX6LEOiTZeX0AM0VbS7bpOYQRh//i85Uf3BLdUG8ORxiTLbCzx6DfdqM9xEZJ3GAofABnRxaINHWwR8g8AvhJEK8YL+X1dARPoKjPqhhGleM+/yjy2rzE+ilwQIIe8AJjy65di6MNn2R+30FITxi76Ga0lflCY1+SoM8yg5EAYKyR6ExiRsFTcVBMGccLGbQXy8aQseR/Vs/0JlZF96mZNcqXepXI7pOwdWNH4NHA8D6fp7w2FTFtVAQ6+BazfyrJiXjjBbs9FdnehnyrHVd1uVxwzzViZkV0CzttSvWkKtMBwPWlH8b8MmMYllKh9qun8gKTq5BGFkYatem+ij40bylkxemhyMtLRFbXtdpvZG7pFXgbLoGDlxNOI/XilBGM=
  - secure: SwUwgHIWX4gTtU4kM47+0/afRhWVD0JbmTwjUPdPt+ax5xLgFdunyqR5IUngEfcmeTmSMq7snve+lDpspGLASmrWnCyeRaNT/xac3FjPoahcMmnQWP+NMNxHY5ZjJLDgmUVBKnBtqXBatip+3/DpPSQSKw5sxweWctqTuWmkIHEFHMFGJzOSKAwuiHyjrThlulcqS1A8ekPCvN4FS+QdzzQqRuvD29dPPuAj03NYK5bogw9PD5vAjZJybq1qj0K/1g4ClZot7YzVZoDvRnTf8J9WhK+lxdQztP4cs3yOmCrGRkiUHi0rrbDTj969Zuc68fR0nCYJn1iVZGXvyVJYLDtvCsI1nO4DF3ral74splp3lO3qP2RHHCKSCuoyolv7/HVD0o7yUS+L3CPOlVubITi2LJHmDV/+eGpPwi8eoIi7sOA7UewFzs/Jw4hICMh1ZtXXP59DoqGtAulq9SoGo1YEPq2APNxzyRl1HEqvNbq9gva9RhNcgTfOhg9cGElMw2K0zFmWa+B5metx+inl3vKFWNuBXplTUag4x/8qnsYhKVYy4SSprwGjD8ngGgcSputN6IUicyuSrX7tFT1eoMpktVHtI0EzREivQE6Thcvsec48v2wdM7G6IDM3Y/wBUZfOtuok/GPrXmwV/wKwHQ/nEWHpUQULDe7v4h63/oE=
  - secure: mRUO3AxIigb/SgacIegAck4CM6uJUwNdnhTLD3VdIbbcrIEMfaDYWCLqma3BGSJmh7kmu7/b1uSGGrsiBj2ZWbsiSc0aaqA8K6KV0A16fjQ8CS7nC2kcuR5ELBWPVklEMgTE3cu3MyTqIkpiT7B+sTfl9WkOse6AfVEGVGivR844wRUd+Q2bxfm+RRc4hEFGZMeHimOacXYrj9Pjq4wt0+0t4DP2DLYfbmWK9zVD3l5FBkoelfn/L/y0NhwKg7lmaXxea1nPPFFuQVPIp7iTTKhpIuLsloyTkJXfx0kjqiewzIqxZsEooPw4HMmfQmcqcIb8uRgNzD2suipD9yNHTzkCdFtZELGt0dXV3b5EAEBtB6MgrcEo3TTFcy8ep+9c9Q1rhdEq/uyicMLu9YsrJimxFCf3A+f8rdwp9yc236GWeraPclQO9FLc6vA7Mx5pGWiX9nPyVq/l7yGzZRRmvAz9Lg7wcZELpEykdtbJ7HqAsaxrX/3TpFNI190fwgEb4HP1bdyjMaHLO48M0cuwwmXVg1pIqolcKZ8ouPcmyE3AP8HROL9xdEqJjDsAHbDn7Y0lX6FgZUW/DdxnwpbDM475sKAU7C66N5olz8jshkHnFyfaYvuW4PU6Lu+Kvq03uspyk/cfqRR8uy9kJP8dhQlsTItCXrNowRA/4CUHtzM=
  - secure: dyX1Wte61F3fviv+7zADkSdltrXG/QxENximLdmnU32DxJbeByPuoYq/8xg0q4zZf611R5hJlCE5bnnA+XSRTqPw4vpWxebpWiC1EoKxlPFGYc5TwEWERISF1d6lH2FjcjAbzat+IkUoq3eavHujPxIhzmIo9TamCwb145ddahCi19D6vDao0eIDvAMKOeB0xN55U7VSbljSHk5lpTCreuNQt9wjdCOmDvsfGKU9PyaXgK4Qs7bK23gWffHjb20AePqJrM/abRvY8UA2zi7r8t1AH/308Ci2SgjdOCnY1a1WELVqXxQqrtIB1ZuWiFQoMG/2pHib1mmZqb+cwq8o6WcSaH8ASYLxce9iaD1nUQhcrEcACjDETHyy9sS+Ar+lF2/BC/Nl0XZnE2ewDa3xBsCw30umdgcotTEvaBGuteDj6b7O+kD6MaFWzO+lmo+CHYQPzjxvZw9PF/NJUryET2+LSlo4ROtom3xiYkySkndHD1y7DjYVROUwdenbx2WkYbI4coZmIqw/sLisEhPK2Ms+eJQh+Jejb8GxTpXQxOgm9yfaQ0s2NkWcu1aq4yfFiM8fMhdhoEAEgouIirYxwBZZziZ5UvFZG5lpQz9RNEiSHdzd3vp+dmX4rzoyOUJGcf9+l4o9zhSSmVvXeFVK2wlqxxZv1EOFXHfOqEc039Y=
